apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: defensive-trout-python 
  janus-idp.io/tekton: defensive-trout-python
  backstage.io/kubernetes-id: defensive-trout-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: defensive-trout-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  